packages:
  - '.'
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
